//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetSad.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int ContractID { get; set; }
        public int ChildID { get; set; }
        public string DocumentName { get; set; }
    
        public virtual Children Children { get; set; }
    }
}
