//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetSad.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsSchedule
    {
        public int EventID { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.TimeSpan EventTime { get; set; }
        public string EventName { get; set; }
        public int UsersID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
